Algoritmo "Apresentacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : José Erinaldo da Fonseca
// Descrição   : Apresentação Hello World
// Autor(a)    : Helder Kennedy Campos
// Data atual  : 31/01/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Helder Kennedy Campos")
escreval("Técnico em desenvolvimento")
escreval("Pará de Minas")

Fimalgoritmo