Algoritmo "Calculos"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : José Erinaldo da Fonseca
// Descrição   : Ler duas notas e fazer a média
// Autor(a)    : Helder Kennedy Campos
// Data atual  : 31/01/2023
Var
// Seção de Declarações das variáveis 
nota1, nota2, media: real

//nome, profissao,  cidade: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor da primeira nota: ")
leia(nota1)
escreva("Digite o valor da segunda nota: ")
leia(nota2)
media <- (nota1 + nota2)/2
escreval("")
escreval("A média dos valores são: ", media)

Fimalgoritmo