Algoritmo "Exercicio4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : José Erinaldo da Fonseca
// Descrição   : condicional para decidir o que fazer
// Autor(a)    : Helder Kennedy Campos
// Data atual  : 01/02/2023
Var
   valor: real



Inicio
   escreva("Informe o valor que você tem sobrando: ")
   leia(valor)
   se (valor > 30) entao
      escreva("Vá ao cinema")
   senao
      escreva("Veja TV")
   fimse
Fimalgoritmo